### ISSUE TITLE
Never throw generic exception

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#11]
https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/gym-service/src/main/java/org/example/controllers/AuthController.java#L25-L30

`UserDetailsService` service throws `AuthenticationException` which seem to be runtime. Why would be catch it and throw generic checked exception from controller? Usually controller shouldn't know what to do with exceptions (especially runtime) and will rethrow through stack trace. It's much better to handle `AuthenticationException` with exception handler there, will be much more understandable and clear.

**Comment by Sanjart3** [comment]
corrected with returning Unauthorized ResponseEntity
