### ISSUE TITLE
DO NOT use star imports

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#12]
https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/gym-service/src/main/java/org/example/controllers/TraineeController.java#L33

Wildcard imports are bad practice, they could lead to huge confusion and make project uncompilable without clear reason. Prefer fullname imports.
https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

**Comment by Sanjart3** [comment]
corrected
