### ISSUE TITLE
Do not print transactionId yourself

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#15]
https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/gym-service/src/main/java/org/example/controllers/TraineeController.java#L67

Why not just configure logging layout (any logging framework support it) to print transaction id from MDC, instead of manually adding it every time?
https://www.baeldung.com/mdc-in-log4j-2-logback

**Comment by Sanjart3** [comment]
resolved the issue using usage of MDC
