### ISSUE TITLE
Exception package

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#16]
https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/gym-service/src/main/java/org/example/utils/exception/AuthenticationException.java#L1

I have no strong preferences, but usually prefer exception to be in root package. Curious why `util`?

**Comment by Sanjart3** [comment]
just, in the beginning I started to design it like this: putting Validations and Exceptions in the util package. Corrected it now
