### ISSUE TITLE
Correlation-id

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#20]
https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/training-event/src/main/java/org/example/trainingevent/filter/SLF4JMDCFilter.java#L23

Service should use transaction id from request when consumer provided it. Using of random values in different microservices makes no sense and will not help to establish distributed tracing. We should be able to find logs from all the services from request chain with single transaction id

**Comment by Sanjart3** [comment]
corrected by getting correlation id from request
