### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#21]
https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/training-event/src/main/java/org/example/trainingevent/TrainingEventApplication.java#L9

Seems this microservice does not have any exception handling. What will happen when exception occur in repository? What consumer will do?

**Comment by Sanjart3** [comment]
implemented
