### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#22]
https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/training-event/src/test/java/org/example/trainingevent/TrainingEventApplicationTests.java#L10

Tests are missing.. I strongly recommend to implement at least several. And do not leave these kind of tests

**Comment by Sanjart3** [comment]
written test for checking creation
