### ISSUE TITLE
Username generator does not create unique usernames

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#26]
https://github.com/Sanjart3/gym-microservice/blob/c37e28ebd2cda016bd488dec5aec0454b9c9828b/gym-service/src/main/java/org/example/utils/UserNameGenerator.java#L17

It depends on in-application hashmap. This will result in duplications when service has several replicas or even restarted. It'd probably ok, if field had constraints, but I don't see them at least on entity.
To generate username we need to actually check them in source of truth

**Comment by Sanjart3** [comment]
this implementation was old one (for previous modules). I have deleted this class now
