### ISSUE TITLE
Not possible status code?

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#28]
https://github.com/Sanjart3/gym-microservice/blob/c37e28ebd2cda016bd488dec5aec0454b9c9828b/training-event/src/main/java/org/example/trainingevent/controllers/TrainingEventController.java#L29

Looking into exception handler, I think any exception will result in 500 (which is not good). So declared 403 can't be received from this endpoint.
Also, 403 is not "Bad request", it's "Forbidden" and should be returned when consumer has no permissions to access/modify data

**Comment by Sanjart3** [comment]
resolved
