### ISSUE TITLE
Empty strings

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#8]
https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/gym-service/src/main/java/org/example/config/FeignClientConfig.java#L21

Often you can receive empty string, which is still invalid case, but will pass this check. Better use `Strings.notBlank()`

**Comment by Sanjart3** [comment]
corrected
