### ISSUE TITLE
Lazy seem to be unjustifiable

### ISSUE THREAD

**Issue by 7kusanagi7** [Sanjart3/gym-microservice#9]
https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/gym-service/src/main/java/org/example/config/JwtTokenFilter.java#L27

Nearly any request will require this filter to execute, there's no point to have its dependencies lazy. Moreover, it affects performance of actual requests. It's always better to take time during start up instead of request execution. Use lazy very carefully, thinking how often dependency could be required

**Comment by 7kusanagi7** [comment]
Same here? https://github.com/Sanjart3/gym-microservice/blob/c510ec3996380f49d0f96cd3d04f390425899f9a/gym-service/src/main/java/org/example/config/WebSecurityConfig.java#L31

**Comment by Sanjart3** [comment]
Actually, first when I did not put Lazy annotation it was giving "Dependency cycle" error, now when I did remove Lazy the error is not appearing)

I have removed unnecessary @Lazy annotations
